[profile.default]
optimizer_runs = 1000000
verbosity = 1
solc_version = '0.8.22'
out = 'out'
libs = ['lib/hyperlane-monorepo/node_modules', 'lib']

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz_runs = 100_000
verbosity = 4

[rpc_endpoints]
mainnet = "${RPC_URL_MAINNET}"

[etherscan]
mainnet = {key = "${ETHERSCAN_KEY}"}
